-- Enable pgvector extension if not already enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Create embeddings table for car_faults
CREATE TABLE IF NOT EXISTS public.car_fault_embeddings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  car_fault_id uuid NOT NULL REFERENCES public.car_faults(id) ON DELETE CASCADE,
  embedding vector(1536), -- text-embedding-3-small produces 1536-dimensional vectors
  text_content text NOT NULL, -- The text that was embedded (title + description)
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  
  UNIQUE (car_fault_id)
);

-- Create index for vector similarity search
CREATE INDEX IF NOT EXISTS car_fault_embeddings_embedding_idx 
ON public.car_fault_embeddings 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Add RLS policies
ALTER TABLE public.car_fault_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.car_fault_embeddings
  FOR SELECT USING (TRUE);

CREATE POLICY "Enable insert for authenticated users only" ON public.car_fault_embeddings
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.car_fault_embeddings
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON public.car_fault_embeddings
  FOR DELETE USING (auth.role() = 'authenticated');

-- Add comments
COMMENT ON TABLE public.car_fault_embeddings IS 'Vector embeddings for car faults to enable semantic similarity search';
COMMENT ON COLUMN public.car_fault_embeddings.embedding IS 'Vector embedding generated by OpenAI text-embedding-3-small (1536 dimensions)';
COMMENT ON COLUMN public.car_fault_embeddings.text_content IS 'The text content that was embedded (title + description)';









