'use client';

import { useState, useEffect } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { useRouter, usePathname } from 'next/navigation';
import Footer from '@/components/Footer';
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is not exported from a client component, so remove or move this if needed elsewhere
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, setUser] = useState<any>(null);
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    console.log('Layout useEffect running');
    const fetchUser = async () => {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        console.log('Initial user fetch:', user);
        setUser(user);
      } catch (error: any) {
        // Don't log AuthSessionMissingError as it's expected for unauthenticated users
        if (error.message !== 'Auth session missing!') {
          console.error('Auth session error in layout:', error);
        }
        setUser(null);
      }
    };

    fetchUser();

    // Listen for auth state changes
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      console.log('Auth state change event:', event, 'session:', session);
      setUser(session?.user || null);
      console.log('User state after auth change:', session?.user || null);
    });

    return () => {
      console.log('Cleaning up auth state change subscription');
      subscription.unsubscribe();
    };
  }, [supabase, router, pathname]);

  return (
    <html lang="en">
      <head>
        <Script defer data-domain="infoneva.com" src="https://plausible.io/js/script.hash.outbound-links.js"></Script>
        <Script id="plausible-inline">
          {`window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Logged-in status indicator (User Icon) - Only show if user is logged in */}
        <div className="fixed top-4 right-4 z-50">
          {user && ( // Conditionally render the Link based on user state
            <Link
              href={`/${pathname?.split('/')[1] || 'en'}/profile`}
              className="flex items-center justify-center w-10 h-10 rounded-full bg-white shadow-md hover:bg-gray-100 transition-colors duration-200"
              aria-label="User Profile"
            >
              {/* SVG for user icon in a circle */}
              <svg className="w-6 h-6 text-gray-600" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/>
              </svg>
            </Link>
          )}
        </div>
        <div className="flex-1">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
